# Generated by Django 6.0.2 on 2026-02-06 09:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=64)),
                ('country', models.TextField(max_length=64)),
                ('latitude', models.TextField(max_length=64)),
                ('longitude', models.TextField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=64)),
                ('password', models.TextField(max_length=64)),
                ('createddate', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='LastCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vieweddate', models.DateField(default=datetime.date.today)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_by_user', to='wetterapp.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_cities', to='wetterapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createddate', models.DateField(default=datetime.date.today)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='wetterapp.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_cities', to='wetterapp.user')),
            ],
        ),
    ]
