# Generated by Django 6.0.2 on 2026-02-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wetterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteCities',
            new_name='FavoriteCitys',
        ),
        migrations.RenameModel(
            old_name='LastCities',
            new_name='LastCitys',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Citys'},
        ),
        migrations.AlterModelOptions(
            name='favoritecitys',
            options={'verbose_name': 'Favorite City', 'verbose_name_plural': 'Favorite Citys'},
        ),
        migrations.AlterModelOptions(
            name='lastcitys',
            options={'verbose_name': 'Last City', 'verbose_name_plural': 'Favorite City'},
        ),
    ]
