# Generated by Django 6.0.2 on 2026-02-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetterapp', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='plz',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.TextField(default='ch', max_length=64),
        ),
    ]
