# Generated by Django 6.0.2 on 2026-02-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wetterapp', '0005_migrate_cities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteCitys',
            new_name='FavoriteCities',
        ),
        migrations.RenameModel(
            old_name='LastCitys',
            new_name='LastCities',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='favoritecities',
            options={'verbose_name': 'Favorite City', 'verbose_name_plural': 'Favorite Cities'},
        ),
        migrations.AlterModelOptions(
            name='lastcities',
            options={'verbose_name': 'Last City', 'verbose_name_plural': 'Last Cities'},
        ),
    ]
