# Generated by Django 6.0.2 on 2026-02-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetterapp', '0007_alter_lastcities_user_alter_favoritecities_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastcities',
            name='username',
            field=models.TextField(default='', max_length=64),
        ),
    ]
