# Generated by Django 6.0.2 on 2026-02-19 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetterapp', '0008_lastcities_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecities',
            name='username',
            field=models.TextField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='lastcities',
            name='vieweddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
